name: LangManager
main: matty\LangManager\Main
version: 1.0.0
api: [5.21.1]
author: matty
description: A language management plugin for PocketMine-MP with multi-language support and variable translation.